name: Development Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy Application
        run: echo "Deploy your app here"

  trigger-automation:
    needs: build-and-deploy

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Automation Repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.AUTOMATION_TOKEN }}" \
          https://api.github.com/repos/Priya7781/Playwright-Automation/dispatches \
          -d '{"event_type":"run-playwright-tests"}'